"""
Agent reconciliation: compares Mission Control's managed agents (from AGENTS.md)
against OpenClaw's registered agents (from ~/.openclaw/agents/ dirs).
Classifies each agent and returns a reconciliation report.
"""
from datetime import datetime, timezone
from pathlib import Path

from openclaw.installer.template_deployer import ROLE_LABELS


# Marker string written to IDENTITY.md by Mission Control's template
MC_PROVENANCE_MARKER = "Generated by OpenClaw Mission Control"


def reconcile(workspace_root: Path) -> dict:
    """
    Compares Mission Control's expected agents vs OpenClaw's registered agents.
    Returns a reconciliation report with agent classifications.

    Report structure:
    {
      "managed": [{"agentId", "displayName", "role", "hasIdentity", "lastActive"}],
      "unmanaged": [{"agentId", "displayName", "hasIdentity", "lastActive"}],
      "runtime": [{"agentId", "dirPath", "hasAuth"}],
      "orphaned": [{"agentId", "dirPath", "hasSessions", "isEmpty"}],
      "test": [{"agentId", "dirPath", "category"}],
      "missing": [{"agentId", "role", "displayName"}],
    }
    """
    # Step 1: Get MC-expected agents from workspace AGENTS.md
    expected = _parse_expected_agents(workspace_root)

    # Step 2: Enumerate actual agents in ~/.openclaw/agents/
    openclaw_agents_dir = Path.home() / ".openclaw" / "agents"
    actual = _enumerate_openclaw_agents(openclaw_agents_dir)

    # Step 3: Classify each agent
    managed = []
    unmanaged = []
    runtime = []
    orphaned = []
    test = []
    missing = []

    # Classify agents that exist in OpenClaw
    for agent_id, agent_data in actual.items():
        classification = _classify_agent(agent_id, agent_data, expected)

        if classification["type"] == "managed":
            managed.append(classification["data"])
        elif classification["type"] == "unmanaged":
            unmanaged.append(classification["data"])
        elif classification["type"] == "runtime":
            runtime.append(classification["data"])
        elif classification["type"] == "orphaned":
            orphaned.append(classification["data"])
        elif classification["type"] == "test":
            test.append(classification["data"])

    # Find missing agents (expected by MC but not in OpenClaw)
    for agent_id, agent_info in expected.items():
        if agent_id not in actual:
            missing.append({
                "agentId": agent_id,
                "role": agent_id,
                "displayName": agent_info.get("displayName", "—"),
            })

    return {
        "managed": managed,
        "unmanaged": unmanaged,
        "runtime": runtime,
        "orphaned": orphaned,
        "test": test,
        "missing": missing,
    }


def _parse_expected_agents(workspace_root: Path) -> dict:
    """
    Reads workspace AGENTS.md to extract the expected agents managed by MC.
    Returns {role_key: {"displayName": "...", "role": "..."}}.
    """
    agents_file = workspace_root / "AGENTS.md"
    if not agents_file.exists():
        return {}

    content = agents_file.read_text(encoding="utf-8", errors="ignore")
    expected = {}

    # Build reverse mapping: label → role_key from ROLE_LABELS
    role_map = {v: k for k, v in ROLE_LABELS.items()}

    current_role = None
    for line in content.splitlines():
        # Check for section headers
        for label, key in role_map.items():
            if f"### {label}" in line:
                current_role = key
                break

        # Extract character name
        if current_role and line.startswith("**Character:**"):
            char = line.split(":", 1)[1].strip()
            # Strip markdown bold formatting (** prefix/suffix) and whitespace
            char = char.strip("* ")
            expected[current_role] = {
                "displayName": char,
                "role": current_role,
            }
            current_role = None

    return expected


def _enumerate_openclaw_agents(openclaw_agents_dir: Path) -> dict:
    """
    Scans ~/.openclaw/agents/ directory and returns agent metadata.
    Returns {agent_id: {"dir", "hasIdentity", "hasAuth", "hasSessions", "sessionCount", "lastModified"}}.
    """
    agents = {}

    if not openclaw_agents_dir.exists():
        return agents

    for agent_dir in openclaw_agents_dir.iterdir():
        if not agent_dir.is_dir():
            continue

        agent_id = agent_dir.name
        identity_file = agent_dir / "IDENTITY.md"
        auth_files = list(agent_dir.glob("agent/auth*.json"))
        sessions_dir = agent_dir / "sessions"

        # Count sessions (active .jsonl files, excluding reset/deleted)
        session_count = 0
        session_files = []
        if sessions_dir.exists():
            for f in sessions_dir.glob("*.jsonl"):
                if not f.name.endswith(".reset") and not f.name.endswith(".deleted"):
                    session_count += 1
                    session_files.append(f)

        # Last modified timestamp
        last_mod = None
        if identity_file.exists():
            last_mod = datetime.fromtimestamp(
                identity_file.stat().st_mtime, tz=timezone.utc
            ).isoformat()
        elif session_files:
            last_mod = datetime.fromtimestamp(
                max(f.stat().st_mtime for f in session_files), tz=timezone.utc
            ).isoformat()

        agents[agent_id] = {
            "dir": str(agent_dir),
            "hasIdentity": identity_file.exists(),
            "hasAuth": len(auth_files) > 0,
            "hasSessions": sessions_dir.exists() and len(list(sessions_dir.glob("*.jsonl"))) > 0,
            "sessionCount": session_count,
            "lastModified": last_mod,
            "isEmpty": _is_agent_dir_empty(agent_dir),
        }

    return agents


def _is_agent_dir_empty(agent_dir: Path) -> bool:
    """Checks if an agent directory is essentially empty (no important files)."""
    # Check for important files
    important_patterns = ["IDENTITY.md", "agent/*", "sessions/*.jsonl"]
    for pattern in important_patterns:
        if agent_dir.glob(pattern):
            return False
    return True


def _classify_agent(agent_id: str, agent_data: dict, expected: dict) -> dict:
    """
    Classifies an agent based on its structure and expected status.
    Returns {"type": "...", "data": {...}}.
    """
    # Check for runtime agents (have agent/ subdir with auth)
    if agent_data["hasAuth"]:
        return {
            "type": "runtime",
            "data": {
                "agentId": agent_id,
                "dirPath": agent_data["dir"],
                "hasAuth": True,
                "chatAvailable": True,  # Runtime agents with auth can chat
                "lastModified": agent_data["lastModified"],
            },
        }

    # Check for test agents (name-based classification)
    # BUT only if the agent is NOT expected by Mission Control — don't flag
    # real managed agents as test just because their name matches a pattern.
    if agent_id not in expected:
        test_category = _classify_as_test(agent_id)
        if test_category:
            return {
                "type": "test",
                "data": {
                    "agentId": agent_id,
                    "dirPath": agent_data["dir"],
                    "category": test_category,
                    "lastModified": agent_data["lastModified"],
                },
            }

    # Check if managed (expected by MC and has identity)
    if agent_id in expected and agent_data["hasIdentity"]:
        # Check for MC provenance marker
        is_managed = _check_mc_provenance(Path(agent_data["dir"]) / "IDENTITY.md")
        if is_managed:
            return {
                "type": "managed",
                "data": {
                    "agentId": agent_id,
                    "displayName": expected[agent_id]["displayName"],
                    "role": agent_id,
                    "hasIdentity": True,
                    "chatAvailable": False,  # Managed agents need routing rules to be chat-available
                    "chatNote": "Requires OpenClaw routing configuration for chat access",
                    "lastModified": agent_data["lastModified"],
                },
            }
        else:
            # Has identity but no MC marker
            return {
                "type": "unmanaged",
                "data": {
                    "agentId": agent_id,
                    "displayName": agent_id,
                    "hasIdentity": True,
                    "lastModified": agent_data["lastModified"],
                },
            }

    # Orphaned: dir exists but no identity or not managed
    return {
        "type": "orphaned",
        "data": {
            "agentId": agent_id,
            "dirPath": agent_data["dir"],
            "hasSessions": agent_data["hasSessions"],
            "isEmpty": agent_data["isEmpty"],
            "lastModified": agent_data["lastModified"],
        },
    }


def _classify_as_test(agent_id: str) -> str | None:
    """
    Returns a test category name if the agent_id matches test patterns.
    Returns None if not a test agent.
    """
    test_patterns = {
        "testprobe": "probe test",
        "testprobe2": "probe test",
        "qc-agent": "quality control",
        "daita": "daita probe",
        "dev": "dev environment",
    }
    return test_patterns.get(agent_id)


def _check_mc_provenance(identity_file: Path) -> bool:
    """Checks if IDENTITY.md contains the Mission Control provenance marker."""
    if not identity_file.exists():
        return False
    try:
        content = identity_file.read_text(encoding="utf-8", errors="ignore")
        return MC_PROVENANCE_MARKER in content
    except Exception:
        return False
